version: '3.7'

services:
  traefik:
    image: "traefik:v2.2.1"
    command:
      - --providers.docker
      - --providers.docker.usebindportip
      - --providers.docker.exposedbydefault=false
      - --serverstransport.insecureskipverify=true
      - --log.level=DEBUG
      - --accesslog=true
      - --entrypoints.ssh.address=:22
      - --entrypoints.openvpn.address=:1194
      - --entrypoints.http.address=:80
      - --entrypoints.http.proxyprotocol.insecure
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --certificatesResolvers.le.acme.email=le@example.com
      - --certificatesResolvers.le.acme.storage=/etc/traefik/acme/acme.json
      - --entrypoints.https.address=:443
      - --entrypoints.https.proxyprotocol.insecure
      - --entrypoints.https.http.tls.certResolver=le
      - --providers.file.directory=/etc/traefik/conf.d
      - --providers.file.watch=true
      - --api.dashboard
      - --api
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./etc:/etc/traefik"
    ports:
      - "2222:22"
      - 80:80
      - 443:443
      - 1194:1194
  consul:
    environment:
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true, \"disable_update_check\": true}"
    image: docker.io/library/consul:1.8.0-beta1
    command: agent -client=0.0.0.0 -server -bootstrap-expect 1 -ui
    volumes:
      - "./etc/data/consul:/consul/data"
  portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./etc/data/portainer:/data"
