version: '3.7'

services:
  app:
    image: "traefik:v2.2.1"
    command:
      - --providers.docker
      - --providers.docker.usebindportip
      - --providers.docker.exposedbydefault=false
      - --log.level=DEBUG
      - --accesslog=true
      - --entryPoints.web.address=:80
      - --entryPoints.web.proxyProtocol.insecure
      - --entryPoints.websecure.address=:443
      - --entryPoints.websecure.proxyProtocol.insecure
      - --certificatesResolvers.le.acme.storage=/etc/traefik/acme/acme.json
      - --providers.file.directory=/etc/traefik/conf.d
      - --providers.file.watch=true
      - --api.dashboard
      - --api
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./etc:/etc/traefik"
  home:
    image: "defn/home"
    entrypoint: [ "sleep", "86400000" ]
    depends_on:
      - pause
    network_mode: service:pause
  pause:
    ports:
      - 80:80
      - 443:443
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.https-redirect.redirectScheme.scheme=https"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=https-redirect@docker"
      - "traefik.http.routers.traefik-api.tls=true"
      - "traefik.http.routers.traefik-api.tls.certresolver=le"
      - "traefik.http.routers.traefik-api.entrypoints=websecure"
      - "traefik.http.routers.traefik-api.rule=Host(`traefik.${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.routers.traefik-dash.tls=true"
      - "traefik.http.routers.traefik-dash.tls.certresolver=le"
      - "traefik.http.routers.traefik-dash.entrypoints=websecure"
      - "traefik.http.routers.traefik-dash.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik-dash.service=dashboard@internal"
