version: '3.7'

services:
  traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-api.rule=Host(`traefik.whoa.bot`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.routers.traefik-dash.rule=Host(`traefik.whoa.bot`)"
      - "traefik.http.routers.traefik-dash.service=dashboard@internal"
  portainer:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.whoa.bot`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  default:
    external:
      name: kitt
