version: '3.7'

services:
  traefik:
    image: "traefik:v2.2.10"
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.usebindportip=false
      - --providers.consulcatalog=true
      - --providers.consulcatalog.exposedbydefault=false
      - --providers.consulcatalog.endpoint.address=${KITT_IP}:8500
      - --providers.consulcatalog.endpoint.datacenter=dc1
      - --providers.consulcatalog.endpoint.token=${CONSUL_HTTP_TOKEN}
      - --serverstransport.insecureskipverify=true
      - --log.level=DEBUG
      - --accesslog=true
      - --entrypoints.ssh.address=:2222
      - --entrypoints.openvpn.address=:1194
      - --entrypoints.http.address=:80
      - --entrypoints.http.proxyprotocol.insecure
      - --certificatesResolvers.le.acme.dnschallenge=true
      - --certificatesResolvers.le.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.le.acme.email=${CF_API_EMAIL}
      - --certificatesResolvers.le.acme.storage=${KITT_ACME_STORAGE:-/etc/traefik/acme/acme.json}
      - --certificatesResolvers.le.acme.dnschallenge.delaybeforecheck=0
      - --certificatesResolvers.le.acme.dnschallenge.resolvers=1.1.1.1
      - --entrypoints.https.address=:443
      - --entrypoints.https.proxyprotocol.insecure
      - --entrypoints.https.http.tls.certResolver=le
      - --providers.file.directory=/etc/traefik/conf.d
      - --providers.file.watch=true
      - --api.dashboard
      - --api
    environment:
      - CF_DNS_API_TOKEN
      - CF_ZONE_API_TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik:/etc/traefik
    depends_on:
      - consul
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - ${KITT_IP}:2222:2222
      - ${KITT_IP}:1194:1194
      - ${KITT_IP}:80:80
      - ${KITT_IP}:443:443
    labels:
      - "id=traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-api.entrypoints=http,https"
      - "traefik.http.routers.traefik-api.rule=HostRegexp(`traefik{domain:.+}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.routers.traefik-dash.entrypoints=http,https"
      - "traefik.http.routers.traefik-dash.rule=HostRegexp(`traefik{domain:.+}`)"
      - "traefik.http.routers.traefik-dash.service=dashboard@internal"
      - "traefik.http.routers.domains.tls=true"
      - "traefik.http.routers.domains.tls.certresolver=le"
      - "traefik.http.routers.domains.tls.domains[0].main=traefik-kitt.${KITT_DOMAIN}"
      - "traefik.http.routers.domains.tls.domains[0].sans=vault.${KITT_DOMAIN},consul.${KITT_DOMAIN}"

volumes:
  traefik:

networks:
  default:
    external:
      name: kitt
