version: '3.7'

services:
  traefik:
    image: "traefik:v2.2.1"
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.usebindportip=false
      - --providers.consulcatalog=true
      - --providers.consulcatalog.exposedbydefault=false
      - --providers.consulcatalog.endpoint.address=169.254.32.1:8500
      - --providers.consulcatalog.endpoint.datacenter=dc1
      - --providers.consulcatalog.endpoint.token=${CONSUL_HTTP_TOKEN}
      - --serverstransport.insecureskipverify=true
      - --log.level=DEBUG
      - --accesslog=true
      - --entrypoints.http.address=:80
      - --entrypoints.http.proxyprotocol.insecure
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --certificatesResolvers.le.acme.dnschallenge=true
      - --certificatesResolvers.le.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.le.acme.email=${CF_API_EMAIL}
      - --certificatesResolvers.le.acme.storage=/etc/traefik/acme/acme.json
      - --certificatesResolvers.le.acme.dnschallenge.delaybeforecheck=0
      - --certificatesResolvers.le.acme.dnschallenge.resolvers=1.1.1.1
      - --entrypoints.https.address=:443
      - --entrypoints.https.proxyprotocol.insecure
      - --entrypoints.https.http.tls.certResolver=le
      - --providers.file.directory=/etc/traefik/conf.d
      - --providers.file.watch=true
      - --api.dashboard
      - --api
    environment:
      - CF_DNS_API_TOKEN
      - CF_ZONE_API_TOKEN
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./etc/traefik:/etc/traefik"
    depends_on:
      - consul
    ports:
      - ${KITT_IP}:80:80
      - ${KITT_IP}:443:443
    labels:
      - "id=traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-api.entrypoints=http,https"
      - "traefik.http.routers.traefik-api.rule=HostRegexp(`traefik{domain:.+}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.routers.traefik-dash.entrypoints=http,https"
      - "traefik.http.routers.traefik-dash.rule=HostRegexp(`traefik{domain:.+}`)"
      - "traefik.http.routers.traefik-dash.service=dashboard@internal"
  traefik-proxy:
    image: letfn/consul-envoy:v1.8.0-v0.14.1
    environment:
      - SERVICE_CONFIG=/config/traefik.hcl
      - CENTRAL_CONFIG=/central_config/traefik.hcl
      - CONSUL_HTTP_ADDR=169.254.32.1:8500
      - CONSUL_GRPC_ADDR=169.254.32.1:8502
      - CONSUL_HTTP_TOKEN
    volumes:
      - "./etc/service_config:/config"
      - "./etc/central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "traefik"]
    network_mode: "service:traefik"
  hera:
    image: aschzero/hera:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.cloudflared:/certs
  cloudflared:
    image: letfn/cloudflared
    restart: always
    volumes:
      - ${HOME}/.cloudflared:/etc/cloudflared
    environment:
      - TUNNEL_URL=https://${KITT_TUNNEL_URL}
      - TUNNEL_HOSTNAME=${KITT_TUNNEL_HOSTNAME}
    depends_on:
      - traefik
      - consul
  zerotier:
    image: letfn/zerotier
    restart: always
    volumes:
      - ./etc/zerotier/zerotier-one:/var/lib/zerotier-one
      - ./etc/zerotier/config:/data/config
    cap_drop:
      - NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    links:
      - traefik
    privileged: true
  consul:
    image: consul:1.8.0
    hostname: kitt-consul
    environment:
      - CONSUL_HTTP_TOKEN
    command: [
      "consul","agent",
      "-config-file=/config/dc1.hcl"]
    volumes:
      - "./etc/consul_config:/config"
      - "./etc/consul_dc1:/consul/data"
    ports:
      - "169.254.32.1:8500:8500"
      - "169.254.32.1:8502:8502"
      - "169.254.32.1:8300:8300"
      - "169.254.32.1:8302:8302/tcp"
      - "169.254.32.1:8302:8302/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consul.entrypoints=https"
      - "traefik.http.routers.consul.rule=HostRegexp(`consul.{domain:.+}`)"
      - "traefik.http.services.consul.loadbalancer.server.port=8500"
  consul-gateway:
    image: letfn/consul-envoy:v1.8.0-v0.14.1
    environment:
      - CONSUL_HTTP_ADDR=169.254.32.1:8500
      - CONSUL_GRPC_ADDR=169.254.32.1:8502
      - CONSUL_HTTP_TOKEN
    command: [
      "consul", "connect", "envoy",
      "-mesh-gateway",
      "-register",
      "-address", "{{GetInterfaceIP \"eth0\"}}",
      "-wan-address", "{{GetInterfaceIP \"eth0\"}}:443",
      "--",
      "-l", "debug"]
    depends_on:
      - consul

networks:
  default:
    external:
      name: kitt
