version: '3.7'

services:
  traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-api.rule=Host(`traefik.whoa.bot`,`traefik.defn.sh`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.routers.traefik-dash.rule=Host(`traefik.whoa.bot`,`traefik.defn.sh`)"
      - "traefik.http.routers.traefik-dash.service=dashboard@internal"
  consul:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consul.rule=Host(`consul.whoa.bot`)"
      - "traefik.http.services.consul.loadbalancer.server.port=8500"
  portainer:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.whoa.bot`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  default:
    external:
      name: kitt
