version: '3.7'

services:
  traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-api.rule=HostRegexp(`traefik.{domain:.+}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.routers.traefik-dash.rule=HostRegexp(`traefik.{domain:.+}`)"
      - "traefik.http.routers.traefik-dash.service=dashboard@internal"
    ports:
      - ${KITT_IP}:22:22
      - ${KITT_IP}:80:80
      - ${KITT_IP}:443:443
      - ${KITT_IP}:1194:1194
  consul:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consul.rule=HostRegexp(`consul.{domain:.+}`)"
      - "traefik.http.services.consul.loadbalancer.server.port=8500"
 
networks:
  default:
    external:
      name: kitt
