version: '3.7'

services:
  traefik:
    image: "traefik:v2.2.1"
    command:
      - --providers.docker
      - --providers.docker.usebindportip=false
      - --providers.docker.exposedbydefault=false
      - --serverstransport.insecureskipverify=true
      - --log.level=DEBUG
      - --accesslog=true
      - --entrypoints.ssh.address=:22
      - --entrypoints.openvpn.address=:1194
      - --entrypoints.http.address=:80
      - --entrypoints.http.proxyprotocol.insecure
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --certificatesResolvers.le.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.le.acme.email=${CF_API_EMAIL}
      - --certificatesResolvers.le.acme.storage=/etc/traefik/acme/acme.json
      - --entrypoints.https.address=:443
      - --entrypoints.https.proxyprotocol.insecure
      - --entrypoints.https.http.tls.certResolver=le
      - --providers.file.directory=/etc/traefik/conf.d
      - --providers.file.watch=true
      - --api.dashboard
      - --api
    environment:
      - CF_DNS_API_TOKEN
      - CF_ZONE_API_TOKEN
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./etc:/etc/traefik"
  traefik-proxy:
    image: letfn/consul-envoy:v1.8.0-v0.14.1
    environment:
      CONSUL_HTTP_ADDR: 169.254.32.1:8500
      CONSUL_GRPC_ADDR: 169.254.32.1:8502
      SERVICE_CONFIG: /config/traefik.hcl
      CENTRAL_CONFIG: /central_config/traefik.hcl
    volumes:
      - "./etc/service_config:/config"
      - "./etc/central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "traefik"]
    network_mode: "service:traefik"
  cloudflared:
    image: letfn/cloudflared
    restart: always
    volumes:
      - ${HOME}/.cloudflared:/etc/cloudflared
    environment:
      - TUNNEL_URL=https://traefik.whoa.bot
      - TUNNEL_HOSTNAME=traefik.defn.sh
    depends_on:
      - consul
  zerotier:
    image: letfn/zerotier
    restart: always
    volumes:
      - ./etc/zerotier/zerotier-one:/var/lib/zerotier-one
      - ./etc/zerotier/config:/data/config
    cap_drop:
      - NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    links:
      - traefik
    privileged: true
  consul:
    image: consul:1.8.0
    command: ["consul","agent","-config-file=/config/dc1.hcl"]
    volumes:
      - "./etc/consul_config:/config"
    ports:
      - "169.254.32.1:8500:8500"
      - "169.254.32.1:8502:8502"
  consul-gateway:
    image: letfn/consul-envoy:v1.8.0-v0.14.1
    environment:
      CONSUL_HTTP_ADDR: 169.254.32.1:8500
      CONSUL_GRPC_ADDR: 169.254.32.1:8502
    command: [
      "consul",
      "connect", "envoy",
      "-mesh-gateway",
      "-register",
      "-address", "{{GetInterfaceIP \"eth0\"}}",
      "-wan-address", "{{GetInterfaceIP \"eth0\"}}:443",
      "--",
      "-l", "debug"]
    depends_on:
      - consul
