version: '3.7'

services:
  traefik:
    image: "traefik:v2.2.1"
    command:
      - --providers.docker
      - --providers.docker.usebindportip
      - --providers.docker.exposedbydefault=false
      - --serverstransport.insecureskipverify=true
      - --log.level=DEBUG
      - --accesslog=true
      - --entrypoints.http.address=:80
      - --entrypoints.http.proxyprotocol.insecure
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --certificatesResolvers.le.acme.email=le@example.com
      - --certificatesResolvers.le.acme.storage=/etc/traefik/acme/acme.json
      - --entrypoints.https.address=:443
      - --entrypoints.https.proxyprotocol.insecure
      - --entrypoints.https.http.tls.certResolver=le
      - --providers.file.directory=/etc/traefik/conf.d
      - --providers.file.watch=true
      - --api.dashboard
      - --api
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./etc:/etc/traefik"
    ports:
      - 80:80
      - 443:443
  portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./etc/data/portainer:/data"
    ports:
      - 9000
  cilium:
    container_name: cilium
    image: docker.io/cilium/cilium:v1.7.3
    command: cilium-agent --kvstore consul --kvstore-opt consul.address=127.0.0.1:8500 -t vxlan --enable-ipv6=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/var/run/cilium
      - /var/run/docker/netns:/var/run/docker/netns
      - /sys/fs/bpf:/sys/fs/bpf
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
      - "NET_RAW"
      - "SYS_ADMIN"
      - "SYS_MODULE"
      - "SYS_RAWIO"
      - "SYS_PACCT"
      - "SYS_NICE"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "AUDIT_CONTROL"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "SYSLOG"
      - "DAC_READ_SEARCH"
      - "LINUX_IMMUTABLE"
      - "NET_BROADCAST"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "SYS_PTRACE"
      - "SYS_BOOT"
      - "LEASE"
      - "WAKE_ALARM"
      - "BLOCK_SUSPEND"
    privileged: true
    depends_on:
      - consul
  cilium_docker:
    container_name: cilium-docker-plugin
    image: docker.io/cilium/docker-plugin:v1.7.3
    command: cilium-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/var/run/cilium
      - /run/docker/plugins:/run/docker/plugins
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
    privileged: true
    depends_on:
      - cilium
  consul:
    container_name: cilium-kvstore
    ports:
      - "8500:8500"
    environment:
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true, \"disable_update_check\": true}"
    image: docker.io/library/consul
    command: agent -client=0.0.0.0 -server -bootstrap-expect 1
