[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[[tls.certificates]]
  certFile = "/etc/traefik/certs/default.pem"
  keyFile = "/etc/traefik/certs/default.key"

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/etc/traefik/certs/default.pem"
      keyFile = "/etc/traefik/certs/default.key"

[http]
  [http.routers]
    [http.routers.consul]
      service = "consul"
      entrypoints = ["https"]
      rule = "HostRegexp(`consul.{domain:.+}`)"
      tls = "true"

  [http.services]
    [http.services.consul.loadBalancer]
      [[http.services.consul.loadBalancer.servers]]
        url = "http://169.254.32.1:8500/"
